"ENV_NAME": "hanabi"
"ENV_KWARGS": {}
"LR": 5.0e-4
"NUM_ENVS": 1024 
"NUM_STEPS": 128 
"TOTAL_TIMESTEPS": 1e10
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"LAYER_WIDTH": 512
"SEED": 30
"ANNEAL_LR": False

# WandB Params
"WANDB_MODE": "disabled"
"ENTITY": ""
"PROJECT": "jaxmarl-hanabi"
