"LR": 1e-5
"NUM_ENVS": 6144 # SET TO NUMBER OF LOADED IPPO POLICIES * 1024
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 2.25e9
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ENV_NAME": "hanabi"
"ENV_KWARGS": {}
"ANNEAL_LR": True
"NUM_CHECKPOINTS": 1
"LOAD_CHECKPOINT": "/workspace/models/hanabi/new/ippo_ff_1/checkpoint_1.pkl,/workspace/models/hanabi/new/ippo_ff_2/checkpoint_1.pkl,/workspace/models/hanabi/new/ippo_ff_3/checkpoint_1.pkl,/workspace/models/hanabi/new/ippo_ff_4/checkpoint_1.pkl,/workspace/models/hanabi/new/ippo_ff_5/checkpoint_1.pkl,/workspace/models/hanabi/new/ippo_ff_6/checkpoint_1.pkl"
# "LOAD_CHECKPOINT": "PATH/TO/IPPO/POLICY/1.pkl,PATH/TO/IPPO/POLICY/2.pkl"
"SAVE_CHECKPOINT": "/workspace/hanabi_saves/ippo_symm_disc/"

# WandB Params
"WANDB_MODE": "online"
"ENTITY": ""
"PROJECT": "jaxmarl-hanabi"