"ENV_NAME": "MPE_simple_spread_v3"
"LR": 5e-4
"NUM_ENVS": 24
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 2e6
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 2
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.3
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 1.0
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ANNEAL_LR": True
"SEED": 30

# WandB Params
"ENTITY": ""
"PROJECT": "jaxmarl-mpe"
"WANDB_MODE" : "disabled"